export const eccAuctionPlayers = [
    { player_name: "Aarav Manohar", role_type: "All Rounder", base_price: 0 },
    { player_name: "Aaron Shenan", role_type: "Batsmen", base_price: 0 },
    { player_name: "Abhinav Rajaraman", role_type: "Batsmen", base_price: 0 },
    { player_name: "Abhishek Chandrukar", role_type: "Bowler", base_price: 0 },
    { player_name: "Abhishek Kumar Singh", role_type: "All Rounder", base_price: 0 },
    { player_name: "Abhishek Ladhad", role_type: "All Rounder", base_price: 0 },
    { player_name: "Aditya Bura", role_type: "Batsmen", base_price: 0 },
    { player_name: "Amit Ranjan", role_type: "Bowler", base_price: 0 },
    { player_name: "Amitoz Bindra", role_type: "All Rounder", base_price: 0 },
    { player_name: "Ankush Ghai", role_type: "WK Batsmen", base_price: 0 },
    { player_name: "Aryan Shinde", role_type: "Bowler", base_price: 0 },
    { player_name: "Ashish Malviya", role_type: "Batsmen", base_price: 0 },
    { player_name: "Deovrat", role_type: "Bowler", base_price: 0 },
    { player_name: "Gaurav Saxena", role_type: "All Rounder", base_price: 0 },
    { player_name: "Gobu", role_type: "Bowler", base_price: 0 },
    { player_name: "Himanshu Singh", role_type: "Bowler", base_price: 0 },
    { player_name: "Hrishikesh Ramesh Babu", role_type: "Bowler", base_price: 0 },
    { player_name: "Irfaan Farooq", role_type: "Bowler", base_price: 0 },
    { player_name: "JK Singh", role_type: "WK Batsmen", base_price: 0 },
    { player_name: "Kamlesh Singh", role_type: "Batsmen", base_price: 0 },
    { player_name: "Karthik Subramanian", role_type: "Batsmen", base_price: 0 },
    { player_name: "Kishan Patel", role_type: "Batsmen", base_price: 0 },
    { player_name: "Mahesh Desai", role_type: "Bowler", base_price: 0 },
    { player_name: "Manirup Sinha", role_type: "Batsmen", base_price: 0 },
    { player_name: "Mark Robinson", role_type: "Bowler", base_price: 0 },
    { player_name: "Milan Moolman", role_type: "All Rounder", base_price: 0 },
    { player_name: "Mohseen Karche", role_type: "Batsmen", base_price: 0 },
    { player_name: "Nisarg Gandhi", role_type: "Bowler", base_price: 0 },
    { player_name: "Obaid Jan", role_type: "Bowler", base_price: 0 },
    { player_name: "Omkar Mandem", role_type: "Batsmen", base_price: 0 },
    { player_name: "Pradeep Patil", role_type: "All Rounder", base_price: 0 },
    { player_name: "Pranav Verma", role_type: "Bowler", base_price: 0 },
    { player_name: "Praneeth Reddy", role_type: "Batsmen", base_price: 0 },
    { player_name: "Prateek Tiwari", role_type: "All Rounder", base_price: 0 },
    { player_name: "Ravi Patel", role_type: "Bowler", base_price: 0 },
    { player_name: "Saurabh Singh", role_type: "Bowler", base_price: 0 },
    { player_name: "Shamshudeen Khoja", role_type: "Bowler", base_price: 0 },
    { player_name: "Shashank Shekhar", role_type: "Batsmen", base_price: 0 },
    { player_name: "Shravan Parakala", role_type: "Batsmen", base_price: 0 },
    { player_name: "Shrey Trehan", role_type: "All Rounder", base_price: 0 },
    { player_name: "Shreyas Ravi", role_type: "Bowler", base_price: 0 },
    { player_name: "Sidhant Jaiswal", role_type: "Bowler", base_price: 0 },
    { player_name: "Soumick Dutta", role_type: "Batsmen", base_price: 0 },
    { player_name: "Soumya", role_type: "Batsmen", base_price: 0 },
    { player_name: "Sudarshan Ramesh", role_type: "All Rounder", base_price: 0 },
    { player_name: "Sudhir Kumar", role_type: "All Rounder", base_price: 0 },
    { player_name: "Sudipt Sahu", role_type: "Bowler", base_price: 0 },
    { player_name: "Tirthak Sanap", role_type: "Batsmen", base_price: 0 },
    { player_name: "Umair Ahmed", role_type: "WK Batsmen", base_price: 0 },
    { player_name: "Umesh", role_type: "WK Batsmen", base_price: 0 },
    { player_name: "Usman", role_type: "Batsmen", base_price: 0 },
    { player_name: "Vijay Krishnan", role_type: "Batsmen", base_price: 0 },
    { player_name: "Viknesh Babu", role_type: "Batsmen", base_price: 0 },
    { player_name: "Vikrant Vashishtha", role_type: "All Rounder", base_price: 0 },
    { player_name: "Vimalraj Venkatesan", role_type: "Batsmen", base_price: 0 },
    { player_name: "Vivek Singh", role_type: "All Rounder", base_price: 0 },
    { player_name: "Yash Kamate", role_type: "WK Batsmen", base_price: 0 },
    { player_name: "Yashwant Singh", role_type: "Bowler", base_price: 0 },
    { player_name: "Zahid Farooq", role_type: "Bowler", base_price: 0 },
  ];